apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gulimall
  name: gulimall-ware
  labels:
    app: gulimall-ware
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-ware
  template:
    metadata:
      labels:
        app: gulimall-ware
    spec:
      containers:
        - name: gulimall-ware
          image: '$REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME-SNAPSHOT-$BUILD_NUMBER'
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: '-Xms=256m -Xmx=400m'
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          ports:
            - protocol: TCP
              containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  namespace: gulimall
  name: gulimall-ware
  labels:
    app: gulimall-ware
spec:
  selector:
    app: gulimall-ware
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30961
  type: NodePort
  sessionAffinity: None